//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.sunhydraulics.machine;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.KeyEvent;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import com.sunhydraulics.machine.R.id;
import com.sunhydraulics.machine.R.layout;
import com.sunhydraulics.machine.model.CategoryChildItem;
import com.sunhydraulics.machine.model.CategoryItem;
import org.androidannotations.api.SdkVersionHelper;
import org.androidannotations.api.builder.ActivityIntentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

@SuppressLint({
    "HandlerLeak"
})
public final class ProductListViewActivity_
    extends ProductListViewActivity
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    public final static String CATEGORY_ITEM_EXTRA = "categoryItem";
    public final static String CATEGORY_CHILD_ITEM_EXTRA = "categoryChildItem";
    private Handler handler_ = new Handler(Looper.getMainLooper());

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
        setContentView(layout.layout_product_list);
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
        injectExtras_();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static ProductListViewActivity_.IntentBuilder_ intent(Context context) {
        return new ProductListViewActivity_.IntentBuilder_(context);
    }

    public static ProductListViewActivity_.IntentBuilder_ intent(android.app.Fragment fragment) {
        return new ProductListViewActivity_.IntentBuilder_(fragment);
    }

    public static ProductListViewActivity_.IntentBuilder_ intent(android.support.v4.app.Fragment supportFragment) {
        return new ProductListViewActivity_.IntentBuilder_(supportFragment);
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        listView = ((ListView) hasViews.findViewById(id.listView));
        init();
    }

    private void injectExtras_() {
        Bundle extras_ = getIntent().getExtras();
        if (extras_!= null) {
            if (extras_.containsKey(CATEGORY_ITEM_EXTRA)) {
                categoryItem = extras_.getParcelable(CATEGORY_ITEM_EXTRA);
            }
            if (extras_.containsKey(CATEGORY_CHILD_ITEM_EXTRA)) {
                categoryChildItem = extras_.getParcelable(CATEGORY_CHILD_ITEM_EXTRA);
            }
        }
    }

    @Override
    public void setIntent(Intent newIntent) {
        super.setIntent(newIntent);
        injectExtras_();
    }

    @Override
    public void showInfo(final String msg) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                ProductListViewActivity_.super.showInfo(msg);
            }

        }
        );
    }

    public static class IntentBuilder_
        extends ActivityIntentBuilder<ProductListViewActivity_.IntentBuilder_>
    {

        private android.app.Fragment fragment_;
        private android.support.v4.app.Fragment fragmentSupport_;

        public IntentBuilder_(Context context) {
            super(context, ProductListViewActivity_.class);
        }

        public IntentBuilder_(android.app.Fragment fragment) {
            super(fragment.getActivity(), ProductListViewActivity_.class);
            fragment_ = fragment;
        }

        public IntentBuilder_(android.support.v4.app.Fragment fragment) {
            super(fragment.getActivity(), ProductListViewActivity_.class);
            fragmentSupport_ = fragment;
        }

        @Override
        public void startForResult(int requestCode) {
            if (fragmentSupport_!= null) {
                fragmentSupport_.startActivityForResult(intent, requestCode);
            } else {
                if (fragment_!= null) {
                    fragment_.startActivityForResult(intent, requestCode);
                } else {
                    super.startForResult(requestCode);
                }
            }
        }

        public ProductListViewActivity_.IntentBuilder_ categoryItem(CategoryItem categoryItem) {
            return super.extra(CATEGORY_ITEM_EXTRA, categoryItem);
        }

        public ProductListViewActivity_.IntentBuilder_ categoryChildItem(CategoryChildItem categoryChildItem) {
            return super.extra(CATEGORY_CHILD_ITEM_EXTRA, categoryChildItem);
        }

    }

}
