//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.sunhydraulics.machine.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import com.sunhydraulics.machine.R.layout;
import com.sunhydraulics.machine.view.RatioImageView;
import org.androidannotations.api.builder.FragmentBuilder;
import org.androidannotations.api.view.HasViews;
import org.androidannotations.api.view.OnViewChangedListener;
import org.androidannotations.api.view.OnViewChangedNotifier;

public final class FeedbackFragment_
    extends com.sunhydraulics.machine.fragment.FeedbackFragment
    implements HasViews, OnViewChangedListener
{

    private final OnViewChangedNotifier onViewChangedNotifier_ = new OnViewChangedNotifier();
    private View contentView_;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        OnViewChangedNotifier previousNotifier = OnViewChangedNotifier.replaceNotifier(onViewChangedNotifier_);
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        OnViewChangedNotifier.replaceNotifier(previousNotifier);
    }

    @Override
    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.layout_feedback_view, container, false);
        }
        return contentView_;
    }

    @Override
    public void onDestroyView() {
        contentView_ = null;
        super.onDestroyView();
    }

    private void init_(Bundle savedInstanceState) {
        OnViewChangedNotifier.registerOnViewChangedListener(this);
    }

    @Override
    public void onViewCreated(View view, Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);
        onViewChangedNotifier_.notifyViewChanged(this);
    }

    public static FeedbackFragment_.FragmentBuilder_ builder() {
        return new FeedbackFragment_.FragmentBuilder_();
    }

    @Override
    public void onViewChanged(HasViews hasViews) {
        ratioImageView = ((RatioImageView) hasViews.findViewById(com.sunhydraulics.machine.R.id.ratioImageView));
        detailView = ((TextView) hasViews.findViewById(com.sunhydraulics.machine.R.id.detailView));
        init();
    }

    public static class FragmentBuilder_
        extends FragmentBuilder<FeedbackFragment_.FragmentBuilder_, com.sunhydraulics.machine.fragment.FeedbackFragment>
    {


        @Override
        public com.sunhydraulics.machine.fragment.FeedbackFragment build() {
            FeedbackFragment_ fragment_ = new FeedbackFragment_();
            fragment_.setArguments(args);
            return fragment_;
        }

    }

}
